# Generated by Django 6.0.5 on 2026-05-19 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorType', models.CharField()),
                ('package', models.CharField()),
                ('category', models.CharField()),
                ('severity', models.CharField()),
                ('generalExplanation', models.CharField()),
                ('generalFix', models.CharField()),
                ('docsUrl', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField()),
                ('explanation', models.CharField()),
                ('fix', models.CharField()),
                ('example', models.CharField()),
                ('severity', models.CharField()),
                ('ErrorTypeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='ErrorCollection.errortype')),
            ],
        ),
    ]
