# Generated by Django 6.0.5 on 2026-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorCollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errortype',
            name='createdByAI',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errortype',
            name='downVotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errortype',
            name='upVotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
