# Generated by Django 6.0.5 on 2026-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorCollection', '0002_errortype_createdbyai_errortype_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errortype',
            name='wilsonScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
