# Generated by Django 6.0.5 on 2026-07-17 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorCollection', '0003_errortype_wilsonscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcase',
            name='AiModel',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='errorcase',
            name='fingerPrint',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errortype',
            name='AiModel',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='errortype',
            name='fingerPrint',
            field=models.CharField(db_index=True, default='abrham', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errortype',
            name='createdByAI',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='downVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='upVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='wilsonScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
