# Generated by Django 6.0.5 on 2026-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorCollection', '0004_errorcase_aimodel_errorcase_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errortype',
            name='fingerPrint',
            field=models.CharField(db_index=True),
        ),
    ]
