# Generated by Django 6.0.5 on 2026-07-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErrorCollection', '0005_alter_errortype_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorcase',
            name='AiModel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='caseName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='example',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='explanation',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='fingerPrint',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='fix',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='errorcase',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='AiModel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='docsUrl',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='downVotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='errorType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='fingerPrint',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='generalExplanation',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='generalFix',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='package',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='severity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='upVotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
